version: "3.6"
services:

  mysql-instance:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Chukwuma123@"
#    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    networks:
      - progress-soft-network
    volumes:
      - app-db:/var/lib/mysql


  progress-soft-test:
    depends_on:
      - mysql-instance
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-instance:3306/progress-soft?autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true"
      SPRING_DATASOURCE_PASSWORD: "Chukwuma123@"
    command: "./mvnw clean install"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    container_name: "progress-soft-app"
    expose:
      - "8090"
    networks:
      - progress-soft-network

networks:
  progress-soft-network:
    name: progress-soft-network

volumes:
  app-db: